FROM node:22.3.0-slim
# ENV HOST 0.0.0.0
# ENV HOST localhost

WORKDIR /opt/svelte
# ADD svelte/package.json /opt/svelte/package.json
# ADD svelte/package-lock.json /opt/svelte/package-lock.json

# ADD dockerfiles/.env .

# RUN npm install

# ADD svelte/.svelte-kit /opt/svelte/.svelte-kit
# ADD svelte/src /opt/svelte/src
# ADD svelte/static /opt/svelte/static
# ADD svelte/tests /opt/svelte/tests
# ADD svelte/.eslintignore /opt/svelte/.eslintignore
# ADD svelte/.eslintrc.cjs /opt/svelte/.eslintrc.cjs
# ADD svelte/.npmrc /opt/svelte/.npmrc
# ADD svelte/.prettierignore /opt/svelte/.prettierignore
# ADD svelte/.prettierrc /opt/svelte/.prettierrc
# ADD svelte/playwright.config.ts /opt/svelte/playwright.config.ts
# ADD svelte/postcss.config.cjs /opt/svelte/postcss.config.cjs
# ADD svelte/svelte.config.js /opt/svelte/svelte.config.js
# ADD svelte/tailwind.config.cjs /opt/svelte/tailwind.config.cjs
# ADD svelte/tsconfig.json /opt/svelte/tsconfig.json
# ADD svelte/vite.config.ts /opt/svelte/vite.config.ts


# RUN npm run build
# EXPOSE 5173
# CMD ["node", "./build"]
