services:
  workspace:
    container_name: ai-agent-company-research-backend
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    environment:
      PYTHONPATH: /workspace
    volumes:
      - ..:/workspace
  splash:
    image: scrapinghub/splash
    container_name: ai-agent-company-research-splash
    # ports:
    #   - 8050:8050
    entrypoint:
     - "python3"
     - "/app/bin/splash"
     - "--proxy-profiles-path"
     - "/etc/splash/proxy-profiles"
     - "--js-profiles-path"
     - "/etc/splash/js-profiles"
     - "--filters-path"
     - "/etc/splash/filters"
     - "--lua-package-path"
     - "/etc/splash/lua_modules/?.lua"
  postgres:
    build:
      context: ..
      dockerfile: .devcontainer/postgres/Dockerfile
    container_name: ai-agent-company-research-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Asia/Tokyo"
    volumes:
      - ai-agent-company-research-postgres-data:/var/lib/postgresql/data
      # - /var/tmp/ai-agent-company-research-postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    # restart: always
    # ports:
    #   - 5432:5432

networks:
  default:
    name: app-net
    external: true

volumes:
  ai-agent-company-research-postgres-data:
    name: ai-agent-company-research-postgres-data

